create table if not exists usuarios (
  id_usuarios bigint generated by default as identity primary key,
  nombreUser text not null,
  emailUser text not null unique,
  contraUser text not null,
  fecha_registroUser date not null default current_date,
  estado integer not null default 1
);

create table if not exists notas (
  id_nota bigint generated by default as identity primary key,
  id_usuario bigint not null references usuarios(id_usuarios) on delete cascade,
  titulo text not null,
  contenido text not null,
  color text not null default '#e8f4ff',
  fecha_creacion timestamp with time zone not null default now(),
  estado integer not null default 1
);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on usuarios to anon, authenticated;
grant select, insert, update, delete on notas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
